# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180225_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post4',
            old_name='Tukusaidiaje',
            new_name='Inquires',
        ),
    ]
